# Generated by Django 4.1.6 on 2023-02-15 16:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='homepage/media'),
        ),
    ]
