# Generated by Django 4.1.6 on 2023-02-15 16:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_news_slug_alter_imageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
