# Generated by Django 4.1.6 on 2023-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeamImg', models.ImageField(upload_to='fixture/media')),
                ('awayTeamImg', models.ImageField(upload_to='fixture/media')),
                ('homeTeamTitle', models.CharField(max_length=50)),
                ('awayTeamTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PremierLeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
