# Generated by Django 4.1.6 on 2023-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premierleaguetable',
            name='drawGame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premierleaguetable',
            name='lossGame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premierleaguetable',
            name='mactchPlayed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premierleaguetable',
            name='teamName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premierleaguetable',
            name='totalPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premierleaguetable',
            name='winGame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
